"use client";

import { useState } from "react";

export interface PdfSection {
  heading: string;
  items: { label: string; value: string }[];
}

interface PdfModalProps {
  title: string;
  sections: PdfSection[];
  onClose: () => void;
}

export default function PdfModal({ title, sections, onClose }: PdfModalProps) {
  const [name, setName] = useState("");
  const [notes, setNotes] = useState("");
  const [generating, setGenerating] = useState(false);

  async function generate() {
    setGenerating(true);
    const { default: jsPDF } = await import("jspdf");

    const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    const col2 = pageWidth / 2;
    let y = 0;

    // ── Header band ──
    pdf.setFillColor(61, 90, 128);
    pdf.rect(0, 0, pageWidth, 36, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text("Property Compass", margin, 16);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.text(title, margin, 26);
    const date = new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" });
    pdf.text(date, pageWidth - margin, 26, { align: "right" });

    y = 46;

    // ── Prepared for ──
    if (name.trim()) {
      pdf.setTextColor(100, 116, 139);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      pdf.text("PREPARED FOR", margin, y);
      y += 5;
      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text(name.trim(), margin, y);
      y += 10;
    }

    // ── Sections ──
    for (const section of sections) {
      // Section heading
      pdf.setFillColor(245, 240, 232);
      pdf.rect(margin, y, pageWidth - margin * 2, 7, "F");
      pdf.setTextColor(61, 90, 128);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "bold");
      pdf.text(section.heading.toUpperCase(), margin + 3, y + 5);
      y += 11;

      // Items in two columns
      let col = 0;
      for (const item of section.items) {
        const x = col === 0 ? margin : col2 + 3;
        pdf.setTextColor(100, 116, 139);
        pdf.setFontSize(8);
        pdf.setFont("helvetica", "normal");
        pdf.text(item.label, x, y);
        pdf.setTextColor(15, 23, 42);
        pdf.setFontSize(10);
        pdf.setFont("helvetica", "bold");
        pdf.text(item.value, x, y + 5);

        if (col === 0) {
          col = 1;
        } else {
          col = 0;
          y += 14;
        }
      }
      if (col === 1) y += 14; // odd item — advance row
      y += 4;
    }

    // ── Notes ──
    if (notes.trim()) {
      y += 2;
      pdf.setFillColor(245, 240, 232);
      pdf.rect(margin, y, pageWidth - margin * 2, 7, "F");
      pdf.setTextColor(61, 90, 128);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "bold");
      pdf.text("NOTES", margin + 3, y + 5);
      y += 11;
      pdf.setTextColor(15, 23, 42);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      const lines = pdf.splitTextToSize(notes.trim(), pageWidth - margin * 2);
      pdf.text(lines, margin, y);
      y += lines.length * 5 + 6;
    }

    // ── Footer ──
    pdf.setDrawColor(231, 224, 214);
    pdf.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);
    pdf.setTextColor(148, 163, 184);
    pdf.setFontSize(7.5);
    pdf.setFont("helvetica", "normal");
    pdf.text(
      "Generated by Property Compass · sextantdigital.com.au · For general information only — not financial advice.",
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );

    const filename = `property-compass-${title.toLowerCase().replace(/\s+/g, "-")}.pdf`;
    pdf.save(filename);
    setGenerating(false);
    onClose();
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ backgroundColor: "rgba(15,23,42,0.55)" }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        className="w-full max-w-md rounded-3xl p-6 shadow-xl"
        style={{ backgroundColor: "#FAF7F2", border: "1px solid #E7E0D6" }}
      >
        <h2 className="text-xl font-semibold" style={{ color: "#0F172A" }}>Save as PDF</h2>
        <p className="mt-1 text-sm" style={{ color: "#64748B" }}>Your results will be saved with your details.</p>

        <div className="mt-5 space-y-4">
          <div>
            <label className="mb-2 block text-sm font-medium" style={{ color: "#3D5A80" }}>Your name</label>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Fiona Graham"
              className="w-full rounded-2xl border bg-white px-4 py-3 text-sm outline-none"
              style={{ borderColor: "#E7E0D6", color: "#0F172A" }}
            />
          </div>
          <div>
            <label className="mb-2 block text-sm font-medium" style={{ color: "#3D5A80" }}>Notes</label>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Add any notes about this property..."
              rows={4}
              className="w-full resize-none rounded-2xl border bg-white px-4 py-3 text-sm outline-none"
              style={{ borderColor: "#E7E0D6", color: "#0F172A" }}
            />
          </div>
        </div>

        <div className="mt-6 flex gap-3">
          <button
            onClick={onClose}
            className="flex-1 rounded-2xl border px-4 py-3 text-sm font-medium transition hover:bg-white"
            style={{ borderColor: "#E7E0D6", color: "#64748B" }}
          >
            Cancel
          </button>
          <button
            onClick={generate}
            disabled={generating}
            className="flex-1 rounded-2xl px-4 py-3 text-sm font-medium text-white transition hover:opacity-90 disabled:opacity-60"
            style={{ backgroundColor: "#3D5A80" }}
          >
            {generating ? "Generating…" : "Download PDF"}
          </button>
        </div>
      </div>
    </div>
  );
}
